export const googleAdsPpc = {
  hero: {
    eyebrow: "Google Ads Management for UK Businesses",
    body: "Search, Display, remarketing and Shopping campaigns planned around the enquiries or sales your business actually needs. We combine account structure, tracking, landing-page advice and ongoing optimisation so ad spend is easier to understand and control.",
    primary: { label: "Discuss Your Google Ads", href: "/contact" },
    secondary: { label: "View PPC Packages", href: "#packages" },
  },
  problems: [
    ["Clicks without useful enquiries", "Traffic is arriving, but search intent, ads or landing pages are not producing the right actions."],
    ["Unclear conversion tracking", "Calls, forms, purchases or lead quality are missing from the reporting, so decisions rely on incomplete data."],
    ["Budget lost to weak searches", "Broad targeting, irrelevant search terms or poorly controlled bids consume spend that could be used more effectively."],
    ["Campaigns that stopped improving", "Accounts need regular search-term reviews, testing and adjustments rather than a one-off launch."],
    ["Ads and landing pages disagree", "The promise in the advert is not continued clearly on the destination page, weakening trust and conversion."],
    ["Reporting without decisions", "A list of impressions and clicks does not explain lead quality, sales value or what should change next."],
  ],
  fit: {
    good: [
      "UK service businesses that want qualified enquiries from active search demand",
      "Ecommerce businesses with accurate product information and a usable purchase journey",
      "Teams able to define a primary conversion such as a call, form, booking or purchase",
      "Businesses with enough budget and time to test, learn and optimise responsibly",
      "Existing advertisers that need clearer structure, measurement or account management",
    ],
    notFit: [
      "Campaigns that must guarantee a fixed number of sales, leads or a specific return",
      "Websites that breach the law, Google Ads policies or required industry approvals",
      "Affiliate offers or sectors the team cannot support responsibly",
      "Businesses unwilling to improve a weak landing page or install suitable measurement",
      "Short emergency campaigns with no time for review and optimisation",
    ],
  },
  capabilities: [
    {
      title: "Google Search Ads",
      body: "Reach people actively searching for relevant products or services, using a controlled keyword, advert and landing-page structure.",
      detail: ["Keyword and intent research", "Campaign and ad-group structure", "Search-term and negative-keyword reviews"],
    },
    {
      title: "Google Display Ads",
      body: "Use visual placements across eligible websites, apps and video inventory to support awareness and audience reach.",
    },
    {
      title: "Google Ads Remarketing",
      body: "Reconnect with eligible previous visitors using audience segments, suitable messages and appropriate consent controls.",
    },
    {
      title: "Google Shopping Ads",
      body: "Promote ecommerce products through Merchant Center feeds, product data and campaign structures designed for Shopping traffic.",
    },
  ],
  process: [
    ["Goals and measurement", "Agree the commercial objective, useful conversion actions, account access and the reporting needed to judge performance."],
    ["Research and account plan", "Review demand, competitors, audiences, keywords, product data and the pages visitors will reach."],
    ["Build and quality checks", "Create the agreed campaign structure, adverts, targeting and measurement, then complete pre-launch checks."],
    ["Launch and learn", "Release campaigns in a controlled way, monitor early search terms and verify that important actions are being recorded."],
    ["Optimise and report", "Adjust bids, budgets, targeting, creative and landing-page recommendations using campaign data and lead or sales feedback."],
  ],
  packages: [
    {
      name: "PPC Seed",
      stage: "Starting account",
      bestFor: "A smaller campaign with the lowest published management allowance and required ad spend.",
      price: "£750",
      features: {
        includedHours: "15",
        requiredAdSpend: "£500",
        contractLength: "3",
        setupTime: "14 days",
        keywordResearch: true,
        accountManager: true,
        meetings: "Monthly",
        onboarding: "24 hours",
        audienceResearch: true,
        campaignSetup: true,
        managementOptimisation: true,
        analyticsSetup: true,
        reporting: true,
        adCopywriting: true,
        conversionOptimisation: false,
        consultancy: false,
      },
    },
    {
      name: "PPC Shoot",
      stage: "Growing campaign",
      bestFor: "A campaign needing more management time plus conversion and consultancy input.",
      price: "£850",
      features: {
        includedHours: "25",
        requiredAdSpend: "£1,500",
        contractLength: "6",
        setupTime: "14 days",
        keywordResearch: true,
        accountManager: true,
        meetings: "Monthly",
        onboarding: "24 hours",
        audienceResearch: true,
        campaignSetup: true,
        managementOptimisation: true,
        analyticsSetup: true,
        reporting: true,
        adCopywriting: true,
        conversionOptimisation: true,
        consultancy: true,
      },
    },
    {
      name: "PPC Sapling",
      stage: "Larger programme",
      bestFor: "A broader account with a higher published ad-spend threshold and management allowance.",
      price: "£1,350",
      features: {
        includedHours: "35",
        requiredAdSpend: "£3,000",
        contractLength: "6",
        setupTime: "14 days",
        keywordResearch: true,
        accountManager: true,
        meetings: "Monthly",
        onboarding: "24 hours",
        audienceResearch: true,
        campaignSetup: true,
        managementOptimisation: true,
        analyticsSetup: true,
        reporting: true,
        adCopywriting: true,
        conversionOptimisation: true,
        consultancy: true,
      },
    },
    {
      name: "PPC Tree",
      stage: "Highest allowance",
      bestFor: "The largest published package, with 60 included hours and the highest required ad spend.",
      price: "£3,300",
      features: {
        includedHours: "60",
        requiredAdSpend: "£5,000",
        contractLength: "6",
        setupTime: "14 days",
        keywordResearch: true,
        accountManager: true,
        meetings: "Monthly",
        onboarding: "24 hours",
        audienceResearch: true,
        campaignSetup: true,
        managementOptimisation: true,
        analyticsSetup: true,
        reporting: true,
        adCopywriting: true,
        conversionOptimisation: true,
        consultancy: true,
      },
    },
  ],
  packageGroups: [
    {
      label: "Budget and account support",
      rows: [
        ["Included hours*", "includedHours"],
        ["Required ad spend", "requiredAdSpend"],
        ["Contract length (months)", "contractLength"],
        ["Set-up time", "setupTime"],
        ["Account manager", "accountManager"],
        ["Meetings", "meetings"],
        ["Onboarding", "onboarding"],
      ],
    },
    {
      label: "Campaign delivery",
      rows: [
        ["Keyword research", "keywordResearch"],
        ["Audience research", "audienceResearch"],
        ["Campaign set-up", "campaignSetup"],
        ["Management and optimisation", "managementOptimisation"],
        ["Analytics set-up", "analyticsSetup"],
        ["Reporting", "reporting"],
        ["Ad copywriting", "adCopywriting"],
        ["Conversion optimisation", "conversionOptimisation"],
        ["Consultancy", "consultancy"],
      ],
    },
  ] as const,
  pricingNotes: [
    "Published package prices are £750, £850, £1,350 and £3,300. Advertising spend is additional.",
    "Required ad spend is £500, £1,500, £3,000 and £5,000 respectively.",
    "Contract lengths are three or six months, and a rolling monthly agreement may be available. Confirm the applicable term in writing.",
    "*Confirm whether included hours and prices are monthly, whether unused time carries forward, and whether VAT is included before publication.",
    "Campaign work cannot guarantee sales, leads or a financial return. Results also depend on the offer, website, competition, budget and sales process.",
  ],
  warnings: [
    ["Give campaigns time to learn", "Allow an initial testing and optimisation period rather than treating PPC as an overnight fix."],
    ["Choose keywords by intent", "High-volume terms are not automatically valuable. Search intent, relevance and conversion evidence should guide decisions."],
    ["Make the destination work", "Ads can deliver relevant visits, but a clear, fast landing page and reliable forms or checkout are needed to convert them."],
  ],
  reasons: [
    ["Campaigns start with a measurable goal", "Calls, forms, bookings, purchases or other useful actions are agreed before optimisation decisions are made."],
    ["Search intent stays visible", "Keywords, search terms and negative keywords are reviewed so the account remains connected to what customers need."],
    ["Ads and landing pages are considered together", "Copy, offer clarity and the destination experience are treated as one journey rather than isolated tasks."],
    ["Reporting leads to next actions", "Performance updates should identify what changed, what was learned and what deserves attention next."],
    ["Website support is available", "WordPress, Shopify and maintenance services can support tracking, feeds, forms and landing-page improvements when separately scoped."],
    ["Limits are explained plainly", "Policy constraints, tracking gaps, uncertain terms and results that cannot be guaranteed are raised before they become surprises."],
  ],
  faqs: [
    ["Why should I use Google Ads?", "Google Ads can place a relevant advert in front of people who are actively searching or browsing eligible inventory. It also provides campaign data that can be used to measure and improve performance, provided conversion tracking is configured correctly. Paid search usually works best alongside [SEO](/search-engine-optimisation) and a landing page built to convert — see [WordPress development](/wordpress-development)."],
    ["Can you set up my Google Ads account?", "Yes. Account or campaign set-up can be scoped using your goals, audience, budget and landing pages. Account set-up may carry an additional fee, so this should be confirmed in the proposal."],
    ["Do you offer ongoing Google Ads management?", "Yes. The published packages include management and optimisation, reporting and monthly meetings. Campaigns are reviewed regularly and commonly need an initial optimisation period."],
    ["What will I need to provide?", "You will normally provide your Google Ads customer ID and information about goals, budgets, audiences and existing measurement. Access should be granted through an approved account invitation; you should not send personal login credentials."],
    ["Do you manage Google Ads for every type of business?", "No. OMH does not support unlawful, unethical or policy-noncompliant campaigns, and may decline affiliate sites, restricted industries or work outside the team's experience."],
    ["Can you guarantee results, sales or leads?", "No. Campaigns can be managed toward agreed goals, but sales and leads also depend on the offer, prices, website, competition, budget and sales process. Any written traffic or performance commitment must be defined precisely in the proposal."],
    ["Is there a limit on campaign keywords?", "There is no fixed keyword limit. We focus on relevant terms that have a realistic chance of producing useful conversions rather than pursuing quantity alone."],
    ["Do you accept white-label work from agencies?", "White-label requests are considered. Agencies should contact support@onlinemarketinghelp.co.uk for the information pack."],
  ],
};
