export const localSeo = {
  hero: {
    eyebrow: "Local SEO services for UK businesses",
    body: "Local search support for businesses that need to be found by people nearby. We connect your Google Business Profile, website, business details, local landing pages, directories, reviews and measurement into one practical programme.",
    primary: { label: "Check My Local Visibility", href: "/contact" },
    secondary: { label: "Discuss Local SEO Support", href: "/contact" },
  },
  signals: [
    ["You are missing from map results", "Your business does not appear reliably when nearby customers search for the service you provide."],
    ["Business details disagree", "Names, addresses, phone numbers, opening hours or categories vary between your website, profile and directories."],
    ["The website lacks local relevance", "Service pages explain what you do but give searchers little confidence about where you work or how to take the next step."],
    ["Reviews are unmanaged", "Recent feedback, owner responses and a repeatable review-request process are missing or inconsistent."],
    ["Directories create noise", "Duplicate, incomplete or low-quality listings make the business harder to verify and maintain."],
    ["Reporting stops at rankings", "Position reports do not explain profile actions, website visits, calls, directions or enquiries."],
  ],
  fit: {
    good: [
      "You serve customers in a defined town, city, region or set of genuine service areas.",
      "Your Google Business Profile and website are important sources of calls, visits or enquiries.",
      "You can provide accurate business details and access to the profile, website and analytics.",
      "You are prepared to improve the website and review process as well as the business profile.",
    ],
    notFit: [
      "You want guaranteed first-place map or local rankings.",
      "The business has no genuine connection to the locations it wants to target.",
      "You want hundreds of thin location pages or low-quality directory links.",
      "No one can approve profile, website or business-detail changes.",
    ],
  },
  benefits: [
    ["More relevant local visits", "Service and location relevance can help the right nearby searchers reach the most useful page, rather than sending every visitor to the homepage."],
    ["A clearer route to enquiry", "Accurate profile details, useful service information and obvious contact options make it easier to call, request directions or enquire."],
    ["Better map visibility", "A complete, accurate and actively maintained Google Business Profile gives Google and customers clearer information about the business."],
    ["Stronger local trust", "Recent reviews, responsible owner responses and consistent business information help customers judge whether to contact you."],
    ["Clearer service-area coverage", "Local research shows how people describe services in the areas you genuinely cover and where the website needs better information."],
    ["More useful reporting", "Profile actions, local landing pages and enquiries provide better context than a ranking report on its own."],
  ],
  workstreams: [
    {
      label: "Profile",
      title: "Google Business Profile",
      body: "Audit the profile, choose accurate categories and improve the information people use before they call, visit or continue to the website.",
      items: ["Profile and category review", "Services, hours and attributes", "Photo, post and update guidance"],
    },
    {
      label: "Website",
      title: "Local pages and signals",
      body: "Connect services to genuine operating areas with useful pages, clear contact details and structured information—not thin pages made only for rankings.",
      items: ["Local keyword and intent research", "Service-area page planning", "NAP and local schema checks"],
    },
    {
      label: "Trust",
      title: "Reviews and citations",
      body: "Improve consistency across relevant directories and establish a responsible process for requesting, monitoring and responding to reviews.",
      items: ["Citation review and clean-up", "Relevant directory submissions", "Review workflow guidance"],
    },
    {
      label: "Measure",
      title: "Local performance",
      body: "Track the actions that matter and explain the limits of local rank data, which can vary by searcher, device, location and time.",
      items: ["Analytics and profile actions", "Local keyword tracking", "Prioritised monthly reporting"],
    },
  ],
  process: [
    ["Define the local market", "Confirm real service areas, priority services, locations, competitors and the actions that matter commercially."],
    ["Audit the footprint", "Review the website, Google Business Profile, NAP consistency, reviews, directories and current local-search visibility."],
    ["Fix the foundations", "Correct agreed profile, website and directory issues, then clarify ownership and access for each asset."],
    ["Build local relevance", "Improve useful local content, citations, internal links, profile activity and the review process where included."],
    ["Measure and refine", "Report on agreed profile and website actions, explain what changed and choose the next evidence-led priorities."],
  ],
  packages: [
    {
      name: "SEO Seed",
      stage: "Local foundation",
      bestFor: "A focused three-month starting scope for one business footprint.",
      price: "£450",
      features: { hours: "10", term: "3", audit: "Included", nap: true, categories: true, keywords: "30", manager: true, meetings: "Monthly", onboarding: "24 hours", actions: true, submissions: "3", directoryReviews: "1", analytics: true, reporting: true, tracking: "20", consultancy: "1" },
    },
    {
      name: "SEO Shoot",
      stage: "Growing local scope",
      bestFor: "More delivery time, keyword coverage and directory work across the same published term.",
      price: "£600",
      features: { hours: "15", term: "3", audit: "14 days", nap: true, categories: true, keywords: "50", manager: true, meetings: "Monthly", onboarding: "24 hours", actions: true, submissions: "7", directoryReviews: "2", analytics: true, reporting: true, tracking: "30", consultancy: "2" },
    },
    {
      name: "SEO Sapling",
      stage: "Broader local programme",
      bestFor: "The largest published allowance, keyword set and directory-submission scope.",
      price: "£700",
      features: { hours: "20", term: "3", audit: "14 days", nap: true, categories: true, keywords: "75", manager: true, meetings: "Monthly", onboarding: "24 hours", actions: true, submissions: "10", directoryReviews: "2", analytics: true, reporting: true, tracking: "50", consultancy: "3" },
    },
  ],
  packageGroups: [
    { label: "Programme", rows: [["Included hours*", "hours"], ["Contract length (months)", "term"], ["Profile and local SEO audit", "audit"], ["Account manager", "manager"], ["Meetings", "meetings"], ["Onboarding", "onboarding"], ["Consultancy", "consultancy"]] },
    { label: "Local delivery", rows: [["NAP and website consistency", "nap"], ["Business Profile category updates", "categories"], ["Local keywords researched", "keywords"], ["Audit actions", "actions"], ["Directory submissions", "submissions"], ["Existing directory reviews", "directoryReviews"], ["Analytics set-up", "analytics"], ["Reporting", "reporting"], ["Keywords tracked", "tracking"]] },
  ] as const,
  notes: [
    "Published package fees are £450, £600 and £700 with a three-month contract shown for each tier.",
    "A rolling monthly agreement may also be available. Confirm the applicable term, notice period and cancellation terms in writing.",
    "*Confirm whether included hours and prices are monthly, whether unused time carries forward and whether VAT is included before publication.",
    "Advertising spend is excluded. Location content, review management, local link work, schema, maps, mobile and voice-search work may also be outside the selected package; the proposal should state the exact scope.",
    "Local positions, calls, visits, enquiries, sales and financial returns cannot be guaranteed. Results also depend on proximity, relevance, prominence, competition, website quality and platform changes.",
  ],
  differentiators: [
    ["A named point of contact", "The original service page states that each package includes an account manager, with monthly meetings and onboarding listed in the package table."],
    ["Profile and website reviewed together", "Local visibility is not treated as a profile-only task. The website, NAP consistency, categories, directories and analytics are included in the published scope table."],
    ["Reporting included", "Analytics set-up, reporting and keyword tracking appear in all three published packages, with the tracked keyword allowance increasing by tier."],
    ["Scope confirmed before work starts", "Some tasks fall outside the package. The proposal confirms the exact tasks, responsibilities, billing frequency and agreement terms before work begins."],
  ],
  faqs: [
    ["What makes OMH’s Local SEO service different?", "The service reviews the Google Business Profile, website, business-detail consistency, directories, local keywords and reporting together rather than treating map visibility as a single isolated task."],
    ["Do you use white-hat SEO methods?", "We work within Google’s guidance. Any proposed tactic should be explained clearly, avoid deceptive practices and protect the long-term reputation of the business. Work beyond a single area is covered by [our wider SEO services](/search-engine-optimisation)."],
    ["How long does local SEO take?", "Changes are often visible within 30 to 90 days, and we recommend allowing at least three months, but timing varies. Competition, proximity, the starting profile, website quality, implementation and review activity all affect progress."],
    ["Can you guarantee local rankings?", "No. Google controls its results, and local visibility varies by location, device, time and search context. Work and reporting standards can be agreed; a specific position, lead count or financial result cannot."],
    ["How long does it take to appear first in local Google searches?", "There is no reliable fixed timeframe and no agency can promise first place. It is worth noting movement may sometimes be visible within a month and may take several months in more competitive markets. Proximity, relevance, prominence, competitors and the quality of the profile and website all affect local results."],
    ["How do I choose a package?", "Choose against the number of locations, quality of the current profile and website, directory clean-up required, competitive market and speed of implementation. The written proposal should confirm every inclusion and exclusion. [Recent local search projects](/case-studies) show how the packages have been used in practice."],
  ],
};
