// Verbatim copy from the live /all-services-price-list/ page (docs/legacy-pages-plan.md
// Phase 2). Wording, feature labels and figures must not be edited.
// `true` = check icon on the live table, `false` = cross icon.

export type PriceCell = string | boolean;
export type PriceTable = {
  id: string;
  title: string;
  tiers: string[];
  rows: { label: string; values: PriceCell[] }[];
  notes: string[];
};

const consultationNote =
  "We will be able to advise on the best package for your business during your initial 30 minute consultation.";
const servicesNote = "As part of your services, we will:";
const accountManagerNote =
  "Provide you with a dedicated account manager who will supervise the team who will be working on your project.";
const progressCallsNote =
  "Schedule Bi-Weekly or Monthly progress calls to give you updates and review the data to give feedback.";
const rollingNote =
  "*Rolling Monthly Agreement Available / Package Excludes Any Advertising Spend.";

const bespokeNote =
  "These packages include 1 monthly consultation to discuss your updates. We do offer bespoke packages where you can contact your account manager on an ad-hoc basis to discuss this please send and enquiry.";
const bespokeFollowUp =
  "We will be able to advise on the best package for your business during your initial 30 minute consultation. As part of your services, we will: Provide you with a dedicated account manager who will supervise the team who will be working on your project. Schedule Bi-Weekly or Monthly progress call to give you updates and review the data to give feedback.";
const rollingShortNote =
  "*Rolling Monthly Agreement Available/Package Excludes Any Advertising Spend.";

export const priceList = {
  eyebrow: "Pricing",
  title: "All Services Price List",
  standfirst:
    "Every package below is taken from the current OMH price list. Jump to the service you need, or talk it through on a 30 minute consultation.",
  tables: [
    {
      id: "wordpress",
      title: "WordPress Development",
      tiers: ["Website Seed", "Website Shoot", "Website Sapling", "Website Tree"],
      rows: [
        { label: "Revisions", values: ["1", "1", "2", "2"] },
        { label: "Content Changes (Hours)", values: [false, false, false, "10"] },
        { label: "Contract Length (Months)", values: ["6*", "12-36", "12-36", "12-36"] },
        { label: "Number Of Pages", values: ["1", "5", "5+", "5+"] },
        { label: "Number Of Stock Images", values: ["5", "10", "20", "30"] },
        { label: "Image Galleries", values: [true, true, true, true] },
        { label: "100% Ownership Rights", values: [true, true, true, true] },
        { label: "SSL certificate", values: [true, true, true, true] },
        { label: "Turn Around Time", values: ["4 weeks", "8 weeks", "TBC", "TBC"] },
        { label: "Additional Security", values: [true, true, true, true] },
        { label: "Meetings", values: ["2", "2", "5", "5"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours", "24 hours"] },
        { label: "1 Year Hosting Included", values: [false, true, true, true] },
        { label: "Google Sitemap", values: [false, true, true, true] },
        { label: "Lead Capture Form Creation", values: [false, true, true, true] },
        { label: "Social Media Links", values: [false, true, true, true] },
        { label: "Copywriting", values: [false, false, false, false] },
        { label: "Cookies Policy Set Up", values: [true, true, true, true] },
        { label: "Website Proof reading", values: [false, false, true, true] },
        { label: "Thank you page set-up", values: [false, false, true, true] },
        { label: "Auto Emailing", values: [false, false, true, true] },
        { label: "Integration with an existing database", values: [false, false, false, true] },
        { label: "Membership Functionality", values: [false, false, false, true] },
        { label: "Password Protected Web Pagss", values: [false, false, false, true] },
        { label: "API integration", values: [false, false, false, true] },
        { label: "Additional Support Hours Post Launch", values: [false, false, false, "10 hours"] },
        { label: "SEO Ready Website", values: [true, true, true, true] },
        { label: "Pricing**", values: ["£200", "£200", "£300", "£500"] },
      ],
      notes: [
        "These prices include 1 website review on completion any additional reviews of the website will be charged at an additional rate.",
        "Website development does not included images or content although we will add your content for you.",
        "Your account manager will recommend the best package based on your business needs including how much content you need to be added.",
        consultationNote,
        servicesNote,
        accountManagerNote,
        progressCallsNote,
        "*Only applicable if pay monthly agreement in place",
        "**Figure Based on Monthly Payment, 50%Depost required",
      ],
    },
    {
      id: "website-designs",
      title: "Website Designs",
      tiers: [],
      rows: [],
      notes: [
        "These packages include 1 monthly consultation to discuss your updates. We do offer bespoke packages where you can contact your account manager on an ad-hoc basis to discuss this please send an enquiry.",
        consultationNote,
        servicesNote,
        accountManagerNote,
        progressCallsNote,
        rollingNote,
      ],
    },
    {
      id: "maintenence",
      title: "Website Maintenance",
      tiers: ["Maintenance Seed", "Maintenance Shoot", "Maintenance Sapling"],
      rows: [
        { label: "Include Hours*", values: ["2", "4", "6"] },
        { label: "Initial Website Audit", values: [true, true, true] },
        { label: "Contract Length (Months)", values: ["3", "6", "6"] },
        { label: "Account Manager", values: [true, true, true] },
        { label: "Meetings", values: ["Monthly", "Monthly", "Monthly"] },
        { label: "WordPress software updates", values: [true, true, true] },
        { label: "WordPress plugin updates", values: [true, true, true] },
        { label: "Cloud backups (weekly)", values: [true, true, true] },
        { label: "Uptime monitoring", values: [true, true, true] },
        { label: "Maintenance report", values: [true, true, true] },
        { label: "Test enquiry forms (monthly)", values: [false, true, true] },
        { label: "Content changes & fixes (hours)", values: ["0", "2", "4"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours"] },
        { label: "Reporting", values: [true, true, true] },
        { label: "Conversion Optimisation", values: [false, false, true] },
        { label: "Consultancy", values: [false, false, true] },
        { label: "Pricing", values: ["£300", "£400", "£500"] },
      ],
      notes: [bespokeNote, bespokeFollowUp, rollingShortNote],
    },
    {
      id: "ppc",
      title: "PPC Advertising Packages",
      tiers: ["PPC Seed", "PPC Shoot", "PPC Sapling", "PPC Tree"],
      rows: [
        { label: "Include Hours*", values: ["15", "25", "35", "60"] },
        { label: "Required Ad Spend", values: ["£500", "£1500", "£3000", "£5000"] },
        { label: "Contract Length (Months)", values: ["3", "6", "6", "6"] },
        { label: "Set-up Time", values: ["14 Days", "14 Days", "14 Days", "14 Days"] },
        { label: "Keyword Research", values: [true, true, true, true] },
        { label: "Account Manager", values: [true, true, true, true] },
        { label: "Meetings", values: ["Monthly", "Monthly", "Monthly", "Monthly"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours", "24 hours"] },
        { label: "Audience Research", values: [true, true, true, true] },
        { label: "Campaign Set-up", values: [true, true, true, true] },
        { label: "Management and optimisation", values: [true, true, true, true] },
        { label: "Analytics Set-up", values: [true, true, true, true] },
        { label: "Reporting", values: [true, true, true, true] },
        { label: "Ad Copywriting", values: [true, true, true, true] },
        { label: "Conversion Optimisation", values: [false, true, true, true] },
        { label: "Consultancy", values: [false, true, true, true] },
        { label: "Pricing**", values: ["£750", "£850", "£1350", "£3300"] },
      ],
      notes: [
        consultationNote,
        servicesNote,
        accountManagerNote,
        progressCallsNote,
        rollingNote,
        "Whilst we work really hard to generate the results you would like, we cannot guarantee financial results.",
        "We do guarantee that we will drive relevant traffic to your website.",
      ],
    },
    {
      id: "seo",
      title: "Search Engine Optimisation Packages",
      tiers: ["SEO Seed", "SEO Shoot", "SEO Sapling", "SEO Tree"],
      rows: [
        { label: "Include Hours*", values: ["15", "30", "45", "75"] },
        { label: "Contract Length (Months)", values: ["6", "6", "9", "9"] },
        { label: "Set-up Time", values: ["14 Days", "14 Days", "14 Days", "14 Days"] },
        { label: "Keyword Research", values: [true, true, true, true] },
        { label: "Account Manager", values: [true, true, true, true] },
        { label: "Meetings", values: ["Monthly", "Monthly", "Monthly", "Monthly"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours", "24 hours"] },
        { label: "Audience Research", values: [true, true, true, true] },
        { label: "Campaign Set-up", values: [true, true, true, true] },
        { label: "Management and optimisation", values: [true, true, true, true] },
        { label: "Analytics Set-up", values: [true, true, true, true] },
        { label: "Reporting", values: [true, true, true, true] },
        { label: "Ad Copywriting", values: [false, true, true, true] },
        { label: "Conversion Optimisation", values: [false, true, true, true] },
        { label: "Consultancy", values: [false, true, true, true] },
        { label: "Pricing**", values: ["£850", "£1600", "£2500", "£4100"] },
      ],
      notes: [
        consultationNote,
        "As part of your services, we will:",
        accountManagerNote,
        progressCallsNote,
        rollingNote,
        "Technical tasks included but not limited to are:",
        "Advanced crawling and extraction, Hreflang recommendations, Page speed analysis, Full & mini technical audits, Log File Analysis Implementation Checks, Staging environment checks, Basic crawling, Sitemap checks & recommendations Schema investigations, Mobile vs Desktop parity checks & recommendations",
      ],
    },
    {
      id: "local-seo",
      title: "Our Local SEO Packages",
      tiers: ["SEO Seed", "SEO Shoot", "SEO Sapling"],
      rows: [
        { label: "Include Hours*", values: ["10", "15", "20"] },
        { label: "Contract Length (Months)", values: ["3", "3", "3"] },
        {
          label: "Local SEO & Google My Business Profile Audit",
          values: [true, "14 Days", "14 Days"],
        },
        { label: "NAP & website consistency updates", values: [true, true, true] },
        { label: "Google My Business Category Updates", values: [true, true, true] },
        { label: "Local Keywords Research", values: ["30", "50", "75"] },
        { label: "Account Manager", values: [true, true, true] },
        { label: "Meetings", values: ["Monthly", "Monthly", "Monthly"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours"] },
        { label: "Local SEO & GMB audit actions", values: [true, true, true] },
        { label: "Submissions on Local directories", values: ["3", "7", "10"] },
        { label: "Review and optimisation of existing local directory", values: ["1", "2", "2"] },
        { label: "Analytics Set-up", values: [true, true, true] },
        { label: "Reporting", values: [true, true, true] },
        { label: "Keyword Tracking", values: ["20", "30", "50"] },
        { label: "Consultancy", values: ["1", "2", "3"] },
        { label: "Pricing", values: ["£450", "£600", "£700"] },
      ],
      notes: [
        consultationNote,
        "As part of your services, we will:",
        accountManagerNote,
        progressCallsNote,
        rollingNote,
        "Depending on the package some of the below tasks may not be included but we will confirm this based on our initial consultation",
        "In our local SEO package, it’s important to note potential exclusions to set clear expectations. Local keyword research, Google My Business optimisation, citations building, on-page SEO with a local focus, and local link building may be excluded. Additionally, services such as creating location-specific content, providing detailed local SEO analytics and reporting, managing local reviews, optimising social media profiles for local reach, implementing local schema markup, and devising tailored local SEO strategies may also fall outside the package. Furthermore, Google Maps optimisation, mobile search optimisation for local queries, and optimising for local voice searches could be excluded. These exclusions allow us to offer a focused package while providing flexibility for clients seeking more comprehensive local SEO efforts.",
      ],
    },
    {
      id: "smm",
      title: "Social Media Management Packages",
      tiers: [
        "Seed Social Media Marketing",
        "Shoot Social Media Marketing",
        "Sapling Social Media Marketing",
      ],
      rows: [
        { label: "Brand Creation", values: [false, true, true] },
        { label: "Contract Length (Months)", values: ["3", "3", "3"] },
        { label: "Facebook Posts", values: ["8", "10", "12"] },
        { label: "Twitter Posts", values: ["8", "12", "15"] },
        { label: "Instagram Posts", values: [false, "10", "12"] },
        { label: "LinkedIn Posts", values: [false, "2", "3"] },
        { label: "Google Posts", values: [false, "0", "2"] },
        { label: "Social Media Page Creation", values: ["1", "1", "2"] },
        { label: "Social Media Page Optimisation", values: ["2", "2", "3"] },
        { label: "Meetings", values: ["Monthly", "Monthly", "Monthly"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours"] },
        { label: "# research", values: [true, true, true] },
        { label: "Organic Following Strategy", values: [false, true, true] },
        { label: "Reporting", values: [true, true, true] },
        { label: "Pricing", values: ["£450", "£700", "£900"] },
      ],
      notes: [
        consultationNote,
        "As part of your services, we will:",
        accountManagerNote,
        progressCallsNote,
        rollingNote,
      ],
    },
    {
      id: "smp",
      title: "Social Media Paid Advertising",
      tiers: [
        "Seed Social Media Paid Advertising",
        "Shoot Social Media Paid Advertising",
        "Sapling Social Media Paid Advertising",
      ],
      rows: [
        { label: "Contract Length (Months)", values: ["3", "3", "3"] },
        { label: "Campaign Planning and Strategy", values: [true, true, true] },
        { label: "Platform Selection and Setup", values: [true, true, true] },
        { label: "Audience Research and Segmentation", values: [true, true, true] },
        { label: "Ad Creative Development", values: [true, true, true] },
        { label: "Ad Campaign Setup", values: [true, true, true] },
        { label: "Social Media Page Creation", values: [false, "1", "2"] },
        { label: "Social Media Page Optimisation", values: [false, "2", "3"] },
        { label: "Meetings", values: ["Monthly", "Monthly", "Monthly"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours"] },
        { label: "Research", values: [true, true, true] },
        { label: "Monitoring and Performance Tracking", values: [false, true, true] },
        { label: "Reporting", values: [true, true, true] },
        { label: "Pricing", values: ["£850", "£1450", "£2100"] },
        { label: "Minimum Required Ad Spend", values: ["£1000", "£3000", "£3000"] },
      ],
      notes: [
        "These packages include copy writing and content creation. The content we create will be inline with your existing brand if you don’t have a brand pallet we can help guide you with this or you can invest in a Branding Package. Our Social Media Marketing packages do not included as standard brand pallet creation so your account manager will discuss the packages available for this service should you need this.",
        "All designs for social media creative come with 1 review. We may use the same content across different platforms but will make sure it is optimised accordingly. The above packages are on a minimum 3 month basis.",
      ],
    },
    {
      id: "logo",
      title: "Logo Design",
      tiers: ["Logo Seed", "Logo Shoot", "Logo Sapling"],
      rows: [
        { label: "Account Manager", values: [true, true, true] },
        { label: "Professional Logo", values: [true, true, true] },
        { label: "Number of Concepts", values: ["1", "1", "2"] },
        { label: "Number of Revisions", values: ["1", "2", "3"] },
        { label: "Source File", values: [false, true, true] },
        { label: "Logo Transparency", values: [true, true, true] },
        { label: "High Resolution", values: [true, true, true] },
        { label: "3D Mockup", values: [false, true, true] },
        { label: "Stationary Designs", values: [false, true, true] },
        { label: "Social Media Kit", values: [false, true, true] },
        { label: "Vector File", values: [false, true, true] },
        { label: "Meetings", values: ["Monthly", "Monthly", "Monthly"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours"] },
        { label: "Reporting", values: [true, true, true] },
        { label: "Conversion Optimisation", values: [false, false, true] },
        { label: "Consultancy", values: [false, false, true] },
        { label: "Pricing", values: ["£750", "£950", "£1600"] },
      ],
      notes: [bespokeNote, bespokeFollowUp, rollingShortNote],
    },
    {
      id: "brochure",
      title: "Brochure Design Packages",
      tiers: ["Brochure Seed", "Brochure Shoot", "Brochure Sapling"],
      rows: [
        { label: "Number of pages", values: ["6", "12", "24"] },
        { label: "Account Manager", values: [true, true, true] },
        { label: "Number of Concepts", values: ["1", "1", "2"] },
        { label: "Number of Revisions", values: ["1", "2", "3"] },
        { label: "Source File", values: [true, true, true] },
        { label: "High Resolution", values: [true, true, true] },
        { label: "Photo Editing", values: [false, true, true] },
        { label: "Vector File", values: [false, true, true] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours"] },
        { label: "Reporting", values: [true, true, true] },
        { label: "Conversion Optimisation", values: [false, false, true] },
        { label: "Consultancy", values: [false, false, true] },
        { label: "Pricing", values: ["£450", "£660", "£1060"] },
      ],
      notes: [bespokeNote, bespokeFollowUp, rollingShortNote],
    },
    {
      id: "writing",
      title: "Writing Packages",
      tiers: ["Writing Seed", "Writing Shoot", "Writing Sapling"],
      rows: [
        { label: "Number of Words", values: ["300", "1000", "2500"] },
        { label: "Keyword Research", values: [false, false, true] },
        { label: "Focus Keywords", values: ["1", "1", "2"] },
        { label: "Number of Revisions", values: ["1", "2", "3"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours"] },
        { label: "Turn around time", values: ["7 Days", "7 Days", "7 Days"] },
        { label: "SEO Optimisation", values: [true, true, true] },
        { label: "Competitor Research", values: [false, false, true] },
        { label: "Pricing", values: ["£450", "£660", "£1060"] },
      ],
      notes: [bespokeNote, bespokeFollowUp, rollingShortNote],
    },
    {
      id: "Shopify",
      title: "Shopify Development",
      tiers: ["Website Seed", "Website Shoot", "Website Sapling", "Website Tree"],
      rows: [
        { label: "Revisions", values: ["1", "1", "2", "2"] },
        { label: "Content Changes (Hours)", values: [false, false, false, "10"] },
        { label: "Contract Length (Months)", values: ["6*", "12-36", "12-36", "12-36"] },
        { label: "Number Of Pages", values: ["1", "5", "5+", "5+"] },
        { label: "Number Of Stock Images", values: ["5", "10", "20", "30"] },
        { label: "Image Galleries", values: [true, true, true, true] },
        { label: "100% Ownership Rights", values: [true, true, true, true] },
        { label: "SSL certificate", values: [true, true, true, true] },
        { label: "Turn Around Time", values: ["4 weeks", "8 weeks", "TBC", "TBC"] },
        { label: "Additional Security", values: [true, true, true, true] },
        { label: "Meetings", values: ["2", "2", "5", "5"] },
        { label: "On Boarding", values: ["24 hours", "24 hours", "24 hours", "24 hours"] },
        { label: "Lead Capture Form Creation", values: [false, true, true, true] },
        { label: "Social Media Links", values: [false, true, true, true] },
        { label: "Copywriting", values: [false, false, false, false] },
        { label: "Cookies Policy Set Up", values: [true, true, true, true] },
        { label: "Website Proof reading", values: [false, false, true, true] },
        { label: "Thank you page set-up", values: [false, false, true, true] },
        { label: "Auto Emailing", values: [false, false, true, true] },
        { label: "Integration with an existing database", values: [false, false, false, true] },
        { label: "Membership Functionality", values: [false, false, false, true] },
        { label: "Password Protected Web Pagss", values: [false, false, false, true] },
        { label: "API integration", values: [false, false, false, true] },
        { label: "Additional Support Hours Post Launch", values: [false, false, false, "10 hours"] },
        { label: "SEO Ready Website", values: [true, true, true, true] },
        { label: "Pricing**", values: ["£300", "£300", "£500", "£700"] },
      ],
      notes: [
        consultationNote,
        servicesNote,
        accountManagerNote,
        progressCallsNote,
        rollingNote,
        "The above pricing does not include the monthly cost of Shopify or any additional apps that may be required.",
      ],
    },
  ] satisfies PriceTable[],
};
