export const shopifyDevelopment = {
  hero: {
    eyebrow: "Shopify Development for UK Businesses",
    title: "Shopify stores built to sell clearly, run reliably and grow with the business",
    body: "Whether you are launching a new store, improving an existing one or moving from another ecommerce platform, we plan and build Shopify websites around products, customers and the way your team needs to work.",
    primary: { label: "Discuss Your Shopify Project", href: "/contact" },
    secondary: { label: "View Website Packages", href: "#packages" },
  },
  needs: [
    "The current store is difficult to navigate, especially on mobile.",
    "Products are hard to find, compare or buy without unnecessary steps.",
    "The theme looks generic or no longer reflects the quality of the brand.",
    "Apps and integrations have made the store slow or difficult to manage.",
    "A migration is needed without losing products, customer data or continuity.",
    "The business needs new functionality that the current setup cannot support.",
    "Marketing campaigns need better product, collection or landing pages.",
  ],
  fit: {
    good: [
      "UK businesses launching a considered ecommerce store",
      "Established retailers redesigning or extending an existing Shopify site",
      "Brands moving from another ecommerce platform to Shopify",
      "Teams needing theme, app, extension or integration work",
      "Businesses that want development connected with SEO and paid marketing",
      "Stores that care about usability, conversion and easier day-to-day management",
    ],
    notFit: [
      "Projects looking only for the cheapest unmodified theme",
      "Stores without product information, imagery or a decision-maker",
      "Businesses expecting development alone to guarantee sales or rankings",
      "Complex migrations that must happen immediately without discovery or testing",
      "Projects with no agreed commercial goal for the store",
    ],
  },
  capabilities: [
    {
      title: "Shopify Store Development",
      body: "A complete Shopify store planned around your catalogue, brand, customer journey and internal workflows.",
      detail: ["Store structure before styling", "Responsive product and collection templates", "A manageable setup for your team"],
    },
    {
      title: "Shopify Theme Development",
      body: "Theme configuration and customisation to improve presentation, usability and the way customers move through the store.",
    },
    {
      title: "Shopify Upgrades & Maintenance",
      body: "Practical fixes, theme updates, performance work and ongoing technical support for an existing store.",
    },
    {
      title: "Shopify Extension Development",
      body: "Focused functionality improvements when the existing store needs more than an off-the-shelf theme can provide.",
    },
    {
      title: "Shopify App Development",
      body: "App planning and development for requirements that cannot be handled reliably by an existing Shopify app.",
    },
    {
      title: "Shopify Migration",
      body: "A controlled move from another ecommerce platform, with data, redirects, content and launch continuity considered early.",
    },
    {
      title: "Shopify Integrations",
      body: "Connections with the databases, fulfilment tools, payment services, marketing platforms and systems your business relies on.",
    },
    {
      title: "Testing & Optimisation",
      body: "Checks across devices, browsers and buying journeys, followed by practical improvements where friction is found.",
    },
    {
      title: "Goal-led Workflow",
      body: "Clear objectives, responsibilities and decision points so the project keeps moving and changes are understood.",
    },
  ],
  process: [
    ["Discovery", "Understand the products, customers, business model, current platform and required functionality."],
    ["Store structure", "Plan navigation, collections, product information, content and the main routes to purchase."],
    ["Theme and UX", "Shape a responsive storefront that reflects the brand and makes products easier to browse and buy."],
    ["Development and integration", "Configure Shopify, build the required functionality and connect approved third-party systems."],
    ["Migration and testing", "Move agreed data where required, test the complete buying journey and prepare redirects and launch checks."],
    ["Launch and support", "Release the store carefully, hand over the agreed setup and plan any maintenance or improvement work."],
  ],
  // Transcribed from the supplied live-page HTML on 27 July 2026. The Shopify
  // table intentionally differs from the WordPress table: it has no hosting or
  // sitemap row, and prices/revision counts are different.
  packages: [
    {
      name: "Website Seed",
      stage: "Focused start",
      bestFor: "A one-page Shopify presence or tightly scoped starter requirement.",
      price: "£300",
      features: {
        revisions: "1",
        contentChanges: false,
        contractLength: "6*",
        pages: "1",
        stockImages: "5",
        imageGalleries: true,
        ownership: true,
        ssl: true,
        turnaround: "4 weeks",
        additionalSecurity: true,
        meetings: "2",
        onboarding: "24 hours",
        leadCapture: false,
        socialLinks: false,
        copywriting: false,
        cookiePolicy: true,
        proofreading: false,
        thankYouPage: false,
        autoEmailing: false,
        databaseIntegration: false,
        membership: false,
        passwordProtected: false,
        apiIntegration: false,
        supportHours: false,
        seoReady: true,
      },
    },
    {
      name: "Website Shoot",
      stage: "Core store site",
      bestFor: "A small business website with the core pages and essential setup shown in the comparison.",
      price: "£300",
      features: {
        revisions: "1",
        contentChanges: false,
        contractLength: "12–36",
        pages: "5",
        stockImages: "10",
        imageGalleries: true,
        ownership: true,
        ssl: true,
        turnaround: "8 weeks",
        additionalSecurity: true,
        meetings: "2",
        onboarding: "24 hours",
        leadCapture: true,
        socialLinks: true,
        copywriting: false,
        cookiePolicy: true,
        proofreading: false,
        thankYouPage: false,
        autoEmailing: false,
        databaseIntegration: false,
        membership: false,
        passwordProtected: false,
        apiIntegration: false,
        supportHours: false,
        seoReady: true,
      },
    },
    {
      name: "Website Sapling",
      stage: "Growing site",
      bestFor: "A broader website requiring more content, revision time and conversion support.",
      price: "£500",
      features: {
        revisions: "2",
        contentChanges: false,
        contractLength: "12–36",
        pages: "5+",
        stockImages: "20",
        imageGalleries: true,
        ownership: true,
        ssl: true,
        turnaround: "TBC",
        additionalSecurity: true,
        meetings: "5",
        onboarding: "24 hours",
        leadCapture: true,
        socialLinks: true,
        copywriting: false,
        cookiePolicy: true,
        proofreading: true,
        thankYouPage: true,
        autoEmailing: true,
        databaseIntegration: false,
        membership: false,
        passwordProtected: false,
        apiIntegration: false,
        supportHours: false,
        seoReady: true,
      },
    },
    {
      name: "Website Tree",
      stage: "Advanced build",
      bestFor: "A larger scope involving advanced functionality, integrations or additional post-launch support.",
      price: "£700",
      features: {
        revisions: "2",
        contentChanges: "10",
        contractLength: "12–36",
        pages: "5+",
        stockImages: "30",
        imageGalleries: true,
        ownership: true,
        ssl: true,
        turnaround: "TBC",
        additionalSecurity: true,
        meetings: "5",
        onboarding: "24 hours",
        leadCapture: true,
        socialLinks: true,
        copywriting: false,
        cookiePolicy: true,
        proofreading: true,
        thankYouPage: true,
        autoEmailing: true,
        databaseIntegration: true,
        membership: true,
        passwordProtected: true,
        apiIntegration: true,
        supportHours: "10 hours",
        seoReady: true,
      },
    },
  ],
  packageGroups: [
    {
      label: "Scope and delivery",
      rows: [
        ["Revisions", "revisions"],
        ["Content changes (hours)", "contentChanges"],
        ["Contract length (months)", "contractLength"],
        ["Web pages", "pages"],
        ["Stock images", "stockImages"],
        ["Image galleries", "imageGalleries"],
        ["Turnaround time", "turnaround"],
        ["Meetings", "meetings"],
        ["Onboarding", "onboarding"],
      ],
    },
    {
      label: "Technical and security",
      rows: [
        ["SSL certificate", "ssl"],
        ["Additional security", "additionalSecurity"],
        ["100% ownership rights", "ownership"],
        ["Cookie policy set-up", "cookiePolicy"],
        ["Password-protected pages", "passwordProtected"],
      ],
    },
    {
      label: "Conversion and content",
      rows: [
        ["Lead capture form", "leadCapture"],
        ["Social media links", "socialLinks"],
        ["SEO-ready website", "seoReady"],
        ["Copywriting", "copywriting"],
        ["Website proofreading", "proofreading"],
        ["Thank-you page set-up", "thankYouPage"],
        ["Auto emailing", "autoEmailing"],
      ],
    },
    {
      label: "Advanced functionality",
      rows: [
        ["Existing database integration", "databaseIntegration"],
        ["Membership functionality", "membership"],
        ["API integration", "apiIntegration"],
        ["Additional support hours post-launch", "supportHours"],
      ],
    },
  ] as const,
  pricingNotes: [
    "Current published Shopify package values are £300, £300, £500 and £700.",
    "Your account manager will recommend a package after reviewing the content, functionality and commercial requirements during an initial 30-minute consultation.",
    "Includes a dedicated account manager and bi-weekly or monthly progress calls.",
    "*A rolling monthly agreement is available. Packages exclude advertising spend.",
    "The current table labels pricing with ** but does not define that note. Confirm the missing pricing condition before publication.",
  ],
  reasons: [
    ["A goal-led workflow", "The store is planned around what customers need to do and what the business needs to manage."],
    ["Development and marketing together", "Shopify work can be considered alongside SEO, paid advertising, landing pages and reporting."],
    ["A practical support route", "Maintenance and improvement work can be scoped after launch instead of being mixed into every build."],
    ["User-friendly handover", "The store should be understandable for the people adding products, processing orders and managing content."],
    ["Testing before launch", "Responsive layouts, forms and buying journeys are checked before the store is handed over."],
    ["Clear commercial scope", "Package values stay visible, while migrations, integrations and custom requirements are reviewed separately."],
  ],
  // [CONFIRM SERVICE DETAIL] — verify the 30-day post-launch support term is current before publication.
  faqs: [
    ["How many people will support my Shopify project?", "A dedicated project contact keeps you updated while the appropriate technical team completes the agreed work."],
    ["How do I start a Shopify project with OMH?", "Send a project brief through the contact page, email support@onlinemarketinghelp.co.uk or call 020 3489 3934. The first discussion is used to understand the store, goals and practical options."],
    ["Can you build a new Shopify store?", "Yes. New-store work can cover structure, theme and user experience, Shopify configuration, approved integrations, testing and launch."],
    ["Can you migrate my existing ecommerce website to Shopify?", "Yes, after the current platform, catalogue, customer data, integrations, URLs and launch risks have been reviewed. Migration work is scoped separately where required."],
    ["How much does Shopify development cost?", "The published packages on this page start at £300. [Recent ecommerce projects](/case-studies) give a sense of typical scope. Migrations, integrations, custom apps and other advanced functionality need a confirmed scope before a final proposal is issued."],
    ["What happens if the project scope or cost changes?", "Any requirement that changes the agreed scope should be explained and approved before extra work begins, so the commercial effect is understood."],
    ["Do you provide Shopify support after launch?", "Thirty days of complimentary support begins at handover, with extended support available afterwards. Longer support is scoped alongside the project."],
    ["Can you support Shopify SEO and marketing?", "Yes. We also provide [SEO services](/search-engine-optimisation) and [paid social advertising](/social-media-paid-advertising), so development can be planned with product discovery, landing pages and campaign tracking in mind."],
  ],
};
