export const siteTestimonials = [
  { name: "Kiera Taylor-Elton", quote: "Great to work with a company that aren’t so pushy on the sales front. Thanks for your help. Look forward to working with you again on the next project.", context: "Review published on the original OMH service pages" },
  { name: "Natasha Kendle", quote: "Online Marketing Help created a logo for my small business. Previously I had an Etsy shop where they were running ads for me and then I opted to have my own WordPress website built for me. The process was so easy and Sarah was fantastic in presenting me with ideas and making the changes I needed to be done. I am now running an SEO package with them and FB paid ads and I am really happy with the results. Thank you Online Marketing Help for your help so far with my new business, I really couldn't have done it without you.", context: "Review published on the original OMH service pages" },
  { name: "Gary Smart", quote: "Been looking around for assistance with my online marketing, it's a bit of a minefield as we all know. Found these guys through a friends recommendation. The attention to detail on my project was a breath of fresh air as I was looking for that personal touch. Good listeners and certainly in my case delivering exactly what I wanted, onwards and upwards.", context: "Review published on the original OMH service pages" },
  { name: "Paige Dalby", quote: "I have wanted to do my own SEO as I wanted to learn I cake across this company and was offered a free mini SEO audit after this I asked for more information. I paid for a full SEO website audit and have been tackling my website SEO. It’s given me some great direction and they have even given me some additional tips. Thank you", context: "Review published on the original OMH service pages" },
  { name: "Sanjay", quote: "Online Marketing Help is a great company to work with. I got SEO done by them and it helped my business a lot by their service. Thanks...I would recommend OMH to anyone looking for SEO services.", context: "Review published on the original OMH service pages" },
  { name: "Ricky Catt", quote: "I had my site built by a different company and things kept breaking. I spoke with Sarah regarding looking at what could be done and she was so polite and professional. She explained that some small fixes could be done and didn’t try to over exaggerate the work that needed done. I had spoken to other agencies and had some very expensive quotes come back, after I got the quote back from Online Marketing Help and I had recurved such great service in answering all of my questions it was a no brainier. Thanks once again for helping me with my site.", context: "Review published on the original OMH service pages" },
  { name: "Tania Smyths", quote: "Really grateful for the support with our ads on google. I was starting to feel like I was going to get anywhere with getting new client. Everything just seemed really confusing and I was scared to just waste money. Glad I found these guys and they are now managing it for me.", context: "Review published on the original OMH service pages" },
  { name: "Karl Weller", quote: "Google is always changing how they handle search engine results. Before I hired Digital Marketing to handle my business’s marketing efforts, I would roll my eyes every time I heard that Google was making yet another change. Now with Online Marketing Helps support I can put my feet up and relax.", context: "Review published on the original OMH service pages" },
] as const;
