export const wordpressMaintenance = {
  hero: {
    eyebrow: "WordPress Maintenance for UK Businesses",
    title: "WordPress maintenance that keeps essential website work under control",
    body: "Updates, backups, monitoring and technical fixes should not depend on someone remembering them after a problem appears. We provide ongoing WordPress maintenance for businesses that need a clearer support route and a more reliable website.",
    primary: { label: "Discuss Website Maintenance", href: "/contact" },
    secondary: { label: "View Maintenance Packages", href: "#packages" },
  },
  issues: [
    ["Server and database errors", "Internal server errors, database connection failures and blank screens."],
    ["Theme and plugin problems", "Broken layouts, update conflicts, WooCommerce issues and unresponsive functionality."],
    ["Login and redirect loops", "Admin lockouts, repeated logouts, redirect errors and posts returning 404 pages."],
    ["SSL and security warnings", "Certificate problems, mixed content, forbidden errors and malware warnings."],
    ["Media and file failures", "Image upload problems, missing temporary folders and files failing to write to disk."],
    ["Email and publishing faults", "Forms not sending, scheduled posts being missed and RSS feed errors."],
    ["Performance limits", "Slow pages, memory exhaustion and maximum execution-time errors."],
    ["Unexpected WordPress faults", "Syntax errors, editor problems and issues that need careful investigation before a fix."],
  ],
  fit: {
    good: [
      "UK businesses relying on WordPress for enquiries, sales or customer information",
      "Teams that want routine updates and backups handled consistently",
      "Websites that need a named route for technical questions and fixes",
      "Businesses that have inherited a site built by another developer",
      "WooCommerce or service websites where downtime creates a commercial problem",
      "Clients that want maintenance connected with development, SEO or paid campaigns",
    ],
    notFit: [
      "Emergency recovery work requested without access or an initial review",
      "Businesses expecting maintenance alone to guarantee rankings or sales",
      "Sites running unsupported software that cannot be updated safely without a wider rebuild",
      "Requests for unlimited development inside a fixed maintenance allowance",
      "Projects where ownership or permission to access the website is unclear",
    ],
  },
  capabilities: [
    {
      title: "WordPress Issue Resolution",
      body: "Investigate and fix agreed WordPress problems, with the likely cause and scope explained before wider work begins.",
      detail: ["Initial triage and reproduction", "A practical fix or recommended route", "Clear notice when work is outside the package"],
    },
    {
      title: "Website Performance",
      body: "Review slow pages, oversized assets, plugin load and technical constraints that may be affecting the experience.",
    },
    {
      title: "Core, Theme & Plugin Updates",
      body: "Apply routine WordPress software updates with a backup and sensible checks around the change.",
    },
    {
      title: "Security & Malware Checks",
      body: "Monitor for obvious risks, investigate warnings and scope any clean-up or hardening work that is required.",
    },
    {
      title: "File & Database Backups",
      body: "Maintain scheduled copies of the website files and database so a recovery route exists when something goes wrong.",
    },
    {
      title: "Theme & Plugin Support",
      body: "Help with existing theme or plugin behaviour, conflicts and functionality changes within the agreed allowance.",
    },
    {
      title: "Uptime Monitoring",
      body: "Monitor site availability so outages can be identified and escalated according to the confirmed support terms.",
    },
    {
      title: "Monthly Assistance Call",
      body: "Review completed maintenance, outstanding concerns and sensible next actions with the client each month.",
    },
    {
      title: "Ongoing Support Route",
      body: "Give the client a clear contact route for maintenance questions, planned requests and technical concerns.",
    },
  ],
  process: [
    ["Access and audit", "Confirm ownership, collect access securely and review the current WordPress, hosting and plugin setup."],
    ["Baseline and backup", "Record the starting position and make sure an agreed recovery copy exists before routine changes."],
    ["Maintenance window", "Apply the updates, content fixes and approved tasks included in the package allowance."],
    ["Checks and monitoring", "Test important pages and forms, review availability and look for issues created by recent changes."],
    ["Report and monthly call", "Summarise completed work, flag risks and agree what needs attention next."],
  ],
  // Transcribed from the supplied live-page HTML on 27 July 2026. The table has
  // three packages and 16 feature rows. Billing frequency and VAT treatment are
  // not stated clearly enough to infer, so they are called out for confirmation.
  packages: [
    {
      name: "Maintenance Seed",
      stage: "Essential cover",
      bestFor: "A smaller WordPress site needing core maintenance and a limited monthly work allowance.",
      price: "£300",
      features: {
        includedHours: "2",
        initialAudit: true,
        contractLength: "3",
        accountManager: true,
        meetings: "Monthly",
        coreUpdates: true,
        pluginUpdates: true,
        cloudBackups: true,
        uptimeMonitoring: true,
        maintenanceReport: true,
        formTesting: false,
        contentChanges: "0",
        onboarding: "24 hours",
        reporting: true,
        conversionOptimisation: false,
        consultancy: false,
      },
    },
    {
      name: "Maintenance Shoot",
      stage: "Ongoing support",
      bestFor: "A business website needing more maintenance time plus monthly form checks.",
      price: "£400",
      features: {
        includedHours: "4",
        initialAudit: true,
        contractLength: "6",
        accountManager: true,
        meetings: "Monthly",
        coreUpdates: true,
        pluginUpdates: true,
        cloudBackups: true,
        uptimeMonitoring: true,
        maintenanceReport: true,
        formTesting: true,
        contentChanges: "2",
        onboarding: "24 hours",
        reporting: true,
        conversionOptimisation: false,
        consultancy: false,
      },
    },
    {
      name: "Maintenance Sapling",
      stage: "Broader assistance",
      bestFor: "A more active website needing the largest published allowance, consultancy and conversion support.",
      price: "£500",
      features: {
        includedHours: "6",
        initialAudit: true,
        contractLength: "6",
        accountManager: true,
        meetings: "Monthly",
        coreUpdates: true,
        pluginUpdates: true,
        cloudBackups: true,
        uptimeMonitoring: true,
        maintenanceReport: true,
        formTesting: true,
        contentChanges: "4",
        onboarding: "24 hours",
        reporting: true,
        conversionOptimisation: true,
        consultancy: true,
      },
    },
  ],
  packageGroups: [
    {
      label: "Time and account support",
      rows: [
        ["Included hours*", "includedHours"],
        ["Contract length (months)", "contractLength"],
        ["Account manager", "accountManager"],
        ["Meetings", "meetings"],
        ["Content changes and fixes (hours)", "contentChanges"],
        ["Onboarding", "onboarding"],
      ],
    },
    {
      label: "WordPress maintenance",
      rows: [
        ["Initial website audit", "initialAudit"],
        ["WordPress software updates", "coreUpdates"],
        ["WordPress plugin updates", "pluginUpdates"],
        ["Cloud backups (weekly)", "cloudBackups"],
        ["Uptime monitoring", "uptimeMonitoring"],
      ],
    },
    {
      label: "Checks and guidance",
      rows: [
        ["Maintenance report", "maintenanceReport"],
        ["Test enquiry forms (monthly)", "formTesting"],
        ["Reporting", "reporting"],
        ["Conversion optimisation", "conversionOptimisation"],
        ["Consultancy", "consultancy"],
      ],
    },
  ] as const,
  pricingNotes: [
    "Current published maintenance package values are £300, £400 and £500.",
    "Each package includes one monthly consultation. Bespoke packages and ad-hoc access to an account manager are available subject to scope.",
    "An initial 30-minute consultation is used to recommend the most suitable package.",
    "Both fixed contract lengths and a rolling monthly agreement are referenced. Confirm which term applies to each package before publication.",
    "*Confirm whether included hours reset monthly, how unused time is treated, whether prices are monthly, and whether VAT is included. Advertising spend is excluded.",
  ],
  reasons: [
    ["Routine care is scheduled", "Updates, backups and checks have an agreed place instead of waiting for a fault to become urgent."],
    ["A named support route", "The client knows where to send a request and who is responsible for keeping it moving."],
    ["Published allowances stay visible", "The comparison shows the included hours and content-fix allowance before a package is discussed."],
    ["Development is available when needed", "Larger fixes can be assessed by the same wider team instead of being forced into routine maintenance."],
    ["Marketing context is not ignored", "Forms, conversion points, SEO work and campaign landing pages can be considered during maintenance."],
    ["Risks are explained plainly", "Unsupported software, access problems and work outside the package are raised rather than hidden."],
  ],
  faqs: [
    ["What does WordPress maintenance include?", "Published inclusions vary by package and cover an initial audit, updates, weekly cloud backups, uptime monitoring, reporting, monthly meetings and an agreed work allowance. Use the comparison for the exact differences."],
    ["Can you fix a WordPress site built by another developer?", "Yes, after the current setup, access, hosting, theme and plugins have been reviewed. Some inherited problems may need separate development work rather than routine maintenance time."],
    ["Can you investigate CSS, theme or plugin problems?", "Yes. Send the website URL and a clear description of the problem. The team can investigate whether the cause is CSS, a theme, a plugin or another part of the setup."],
    ["What access do you need before starting?", "WordPress administrator access is normally required. Hosting, domain or other platform access may also be needed depending on the task. Credentials should only be shared through the approved secure process."],
    ["Are backups, security and monitoring included?", "All three published packages show weekly cloud backups, uptime monitoring and routine WordPress updates. Any additional security, malware removal, recovery or response-time commitment must be confirmed in the scope."],
    ["Can you also help with SEO or a new website?", "Yes. We also provide [WordPress development](/wordpress-development), [SEO](/search-engine-optimisation) and [Google Ads management](/google-adwords-ppc). Those services are scoped separately from the maintenance allowance."],
    ["Do you manage hosting and domain renewals?", "Hosting and domain support can be provided, but the exact offer and charges should be confirmed during the consultation."],
    ["Is there a warranty or money-back guarantee?", "Both a 30-day warranty and a money-back guarantee are referenced. The written coverage, exclusions and claim process must be confirmed before either promise is published as a package term."],
  ],
};
