export const wordpressDevelopment = {
  hero: {
    eyebrow: "WordPress Development for UK Businesses",
    title: "WordPress websites built to support enquiries, sales and long-term growth",
    body: "Your website should be easy to manage, fast to load, secure, and built around the actions you want visitors to take. We build and improve WordPress websites for UK businesses that need a reliable site, clearer structure and better conversion support.",
    primary: { label: "Book a WordPress Consultation", href: "/contact" },
    secondary: { label: "View Website Packages", href: "#packages" },
  },
  pains: [
    "The site looks outdated compared with the quality of the business.",
    "Visitors arrive but do not enquire, call or buy.",
    "The website is difficult to update without developer help.",
    "Forms, plugins or layouts keep breaking.",
    "The site is slow on mobile or performs poorly.",
    "The structure is confusing for users and search engines.",
    "Paid campaigns need better landing pages.",
  ],
  fit: {
    good: [
      "UK-based small businesses and established service businesses",
      "Ecommerce businesses using or considering WordPress or WooCommerce",
      "Businesses redesigning an outdated WordPress site",
      "Companies needing custom features, integrations or better structure",
      "Teams that want web development connected with marketing",
      "Businesses that care about enquiries, sales, performance and usability",
    ],
    notFit: [
      "Businesses looking only for the cheapest possible website",
      "Projects with no clear goal, content or decision-maker",
      "One-page websites with no plan to grow",
      "Businesses expecting guaranteed rankings from development alone",
      "Urgent same-day rebuilds that cannot be planned properly",
    ],
  },
  capabilities: [
    {
      title: "Custom WordPress Development",
      body: "For businesses that need a website designed around their goals, content, brand and customer journey.",
      size: "large",
    },
    {
      title: "WordPress Redesigns",
      body: "For existing websites that need stronger structure, improved mobile experience, better UX and cleaner design.",
      size: "medium",
    },
    {
      title: "Plugins, Multisite and Integrations",
      body: "Custom plugins, WordPress Multisite, forms, booking and quote systems, membership features, protected content, dashboards and third-party or API integrations.",
      size: "medium",
    },
    {
      title: "Landing Pages",
      body: "For Google Ads, Meta Ads, SEO campaigns, service launches and local lead-generation campaigns.",
      size: "small",
    },
    {
      title: "Technical Improvements",
      body: "Speed, security, plugin clean-up, broken layouts, form issues, tracking, mobile fixes and performance improvements.",
      size: "small",
    },
    {
      title: "Ongoing Maintenance",
      body: "Updates, backups, monitoring, support and post-launch improvements, offered as an add-on after the development work.",
      size: "small",
    },
  ],
  process: [
    ["Discovery", "Understand the business, audience, website goals, current problems and required functionality."],
    ["Structure", "Plan pages, navigation, content blocks, customer journey and conversion points."],
    ["Design", "Create a responsive design that reflects the brand and supports the actions visitors should take."],
    ["Development", "Build the WordPress site with clean structure, speed, security, usability and future management in mind."],
    ["Launch and Support", "Test carefully, launch properly and provide support for updates, improvements or ongoing maintenance."],
  ],
  // Every value below is transcribed from the live pricing table at
  // /wordpress-development/. Booleans render as included/not-included ticks;
  // strings render verbatim. Seed and Shoot are BOTH £200 on the live page —
  // confirmed, not a scrape error.
  packages: [
    {
      name: "Website Seed",
      stage: "Starter presence",
      bestFor: "Best for a small starter website, simple campaign page or one-page presence.",
      price: "£200",
      features: {
        revisions: "1",
        contentChanges: false,
        contractLength: "6*",
        pages: "1",
        stockImages: "5",
        imageGalleries: true,
        turnaround: "4 weeks",
        meetings: "2",
        onboarding: "24 hours",
        ssl: true,
        additionalSecurity: true,
        ownership: true,
        cookiePolicy: true,
        passwordProtected: false,
        hosting: false,
        sitemap: false,
        leadCapture: false,
        thankYouPage: false,
        autoEmailing: false,
        socialLinks: false,
        seoReady: true,
        copywriting: false,
        proofreading: false,
        databaseIntegration: false,
        membership: false,
        apiIntegration: false,
        supportHours: false,
      },
    },
    {
      name: "Website Shoot",
      stage: "Core business site",
      bestFor: "Best for a small business website with core service pages and essential setup.",
      price: "£200",
      features: {
        revisions: "1",
        contentChanges: false,
        contractLength: "12–36",
        pages: "5",
        stockImages: "10",
        imageGalleries: true,
        turnaround: "8 weeks",
        meetings: "2",
        onboarding: "24 hours",
        ssl: true,
        additionalSecurity: true,
        ownership: true,
        cookiePolicy: true,
        passwordProtected: false,
        hosting: true,
        sitemap: true,
        leadCapture: true,
        thankYouPage: false,
        autoEmailing: false,
        socialLinks: true,
        seoReady: true,
        copywriting: false,
        proofreading: false,
        databaseIntegration: false,
        membership: false,
        apiIntegration: false,
        supportHours: false,
      },
    },
    {
      name: "Website Sapling",
      stage: "Growing site",
      bestFor: "Best for growing businesses that need more structure, extra content and stronger conversion support.",
      price: "£300",
      features: {
        revisions: "1",
        contentChanges: false,
        contractLength: "12–36",
        pages: "5+",
        stockImages: "20",
        imageGalleries: true,
        turnaround: "TBC",
        meetings: "5",
        onboarding: "24 hours",
        ssl: true,
        additionalSecurity: true,
        ownership: true,
        cookiePolicy: true,
        passwordProtected: false,
        hosting: true,
        sitemap: true,
        leadCapture: true,
        thankYouPage: true,
        autoEmailing: true,
        socialLinks: true,
        seoReady: true,
        copywriting: false,
        proofreading: true,
        databaseIntegration: false,
        membership: false,
        apiIntegration: false,
        supportHours: false,
      },
    },
    {
      name: "Website Tree",
      stage: "Larger build",
      bestFor: "Best for larger websites, advanced features, integrations, content depth or more complex requirements.",
      price: "£500",
      features: {
        revisions: "1",
        contentChanges: "1",
        contractLength: "12–36",
        pages: "5+",
        stockImages: "30",
        imageGalleries: true,
        turnaround: "TBC",
        meetings: "5",
        onboarding: "24 hours",
        ssl: true,
        additionalSecurity: true,
        ownership: true,
        cookiePolicy: true,
        passwordProtected: true,
        hosting: true,
        sitemap: true,
        leadCapture: true,
        thankYouPage: true,
        autoEmailing: true,
        socialLinks: true,
        seoReady: true,
        copywriting: false,
        proofreading: true,
        databaseIntegration: true,
        membership: true,
        apiIntegration: true,
        supportHours: "10 hours",
      },
    },
  ],
  // The full comparison, grouped so 27 rows stay scannable. Order within groups
  // is ours; every row and value is preserved from the live table.
  packageGroups: [
    {
      label: "Scope and delivery",
      rows: [
        ["Revisions", "revisions"],
        ["Content changes (hours)", "contentChanges"],
        ["Contract length (months)", "contractLength"],
        ["Web pages", "pages"],
        ["Stock images", "stockImages"],
        ["Image galleries", "imageGalleries"],
        ["Turnaround time", "turnaround"],
        ["Meetings", "meetings"],
        ["Onboarding", "onboarding"],
      ],
    },
    {
      label: "Technical and security",
      rows: [
        ["SSL certificate", "ssl"],
        ["Additional security", "additionalSecurity"],
        ["100% ownership rights", "ownership"],
        ["Cookie policy set-up", "cookiePolicy"],
        ["Password-protected pages", "passwordProtected"],
        ["1 year hosting included", "hosting"],
        ["Google sitemap", "sitemap"],
      ],
    },
    {
      label: "Conversion and marketing",
      rows: [
        ["Lead capture form", "leadCapture"],
        ["Thank-you page set-up", "thankYouPage"],
        ["Auto emailing", "autoEmailing"],
        ["Social media links", "socialLinks"],
        ["SEO-ready website", "seoReady"],
        ["Copywriting", "copywriting"],
        ["Website proofreading", "proofreading"],
      ],
    },
    {
      label: "Advanced functionality",
      rows: [
        ["Existing database integration", "databaseIntegration"],
        ["Membership functionality", "membership"],
        ["API integration", "apiIntegration"],
        ["Additional support hours post-launch", "supportHours"],
      ],
    },
  ] as const,
  // Shown under the table. Fixes the live page's typos ("Depost", "upto") and
  // keeps every disclaimer.
  pricingNotes: [
    "Prices preserve the current published values. Website Seed and Website Shoot are both £200.",
    "These prices include one website review on completion; any additional reviews are charged at an additional rate.",
    "Website development does not include images or content, although we will add your content for you.",
    "Your account manager recommends the best package for your business needs and content, and will advise during your initial 30-minute consultation.",
    "As part of your services you get a dedicated account manager and bi-weekly or monthly progress calls to review data and give feedback.",
    "*Only applicable if a pay-monthly agreement is in place. **Figure based on monthly payment; 50% deposit required.",
  ],
  // Grouped so the section can render as ruled rows + inline chips rather than
  // another card grid. Covers the inclusions listed in the page brief §7.
  included: [
    [
      "Planning and project management",
      "Someone owns the project and keeps it moving.",
      ["Account manager", "Consultation", "Progress calls", "Scope guidance"],
    ],
    [
      "Design and development",
      "The build itself, across every screen size.",
      ["Page layouts", "Responsive design", "WordPress build", "Content setup where supplied"],
    ],
    [
      "Technical setup",
      "The parts that must be right before launch.",
      [
        "SSL certificate",
        "Google sitemap",
        "Lead capture form",
        "Thank-you page",
        "Cookie policy setup",
        "Auto emailing",
        "Database and API integration where included",
      ],
    ],
    [
      "SEO and marketing foundation",
      "So the site can be found and measured after launch.",
      ["SEO-ready structure", "Sensible heading order", "Tracking-ready layout", "Campaign landing pages where relevant"],
    ],
    [
      "Post-launch support",
      "What happens once the site is live.",
      ["One website review", "Support hours where included", "Maintenance option", "Updates where included"],
    ],
  ] as const,
  reasons: [
    ["Development and marketing under one roof", "Your site can be planned with SEO, paid advertising, lead capture and reporting in mind."],
    ["Built around enquiries and sales", "Layouts support actions such as calls, form submissions, quote requests, bookings or purchases."],
    ["Easier to manage after launch", "The site is structured so normal updates do not require a developer for every small change."],
    ["Technical support after launch", "WordPress needs updates, security checks and ongoing care."],
    ["Clear communication", "You understand what is happening, what is needed from you and what happens next."],
    ["SEO-ready foundations", "Clean structure, sensible headings, fast-loading pages and a proper technical base."],
  ],
  faqs: [
    ["How much does a WordPress website cost?", "Package prices are shown on this page, starting at £200. Final scope depends on pages, content, functionality and support requirements."],
    ["How long does a WordPress website take?", "Current package turnaround times range from 4 weeks to 8 weeks where confirmed. Larger packages are marked TBC until the scope is reviewed."],
    ["Can you redesign my existing WordPress site?", "Yes, once the current site can be reviewed and the goals for the redesign are clear."],
    ["Will I be able to edit the website myself?", "WordPress is built to be manageable, but advanced layouts, integrations and features may still need support."],
    ["Do you provide hosting and maintenance?", "One year of hosting is included from the Website Shoot package upwards. Maintenance can be added depending on the package and support requirements. The development project stays focused on the website build."],
    ["Can you help with SEO after launch?", "Yes. OMH also provides SEO and digital marketing services, so the website can be supported after launch."],
    ["Can you fix a website built by another developer?", "Yes, after a review of the current setup, plugins, theme and hosting."],
    ["What do you need from me before starting?", "Business goals, content, branding, website examples, required pages, required functionality and decision-maker input."],
  ],
};
